import type {
  AppNotification,
  Emergency,
  FoundPerson,
  HazardZone,
  Hospital,
  Message,
  MissingPerson,
  Resource,
  Road,
  Shelter,
} from './types';

// Coordinates centered on a fictional flood-affected city
export const MAP_CENTER: [number, number] = [26.9124, 75.7873]; // ~Jaipur-ish
export const MAP_ZOOM = 14;

export const initialEmergencies: Emergency[] = [
  {
    id: 'E-102',
    disasterType: 'flood',
    description:
      'Water has entered our house. 6 people are trapped. My grandmother cannot walk and one person is injured.',
    location: 'Zone A, Riverside Area',
    coords: { lat: 26.915, lng: 75.78 },
    peopleAffected: 6,
    injured: true,
    vulnerable: true,
    immediateDanger: true,
    priority: 'critical',
    status: 'resource_assigned',
    assignedTeam: 'Rescue Team R-02',
    assignedResource: 'Rescue Vehicle R-01',
    eta: 6,
    createdAt: Date.now() - 1000 * 60 * 8,
    updates: [
      { time: Date.now() - 1000 * 60 * 8, text: 'Emergency reported by citizen.' },
      { time: Date.now() - 1000 * 60 * 7, text: 'AI-assisted triage completed: CRITICAL.' },
      { time: Date.now() - 1000 * 60 * 6, text: 'Rescue Vehicle R-01 assigned.' },
      { time: Date.now() - 1000 * 60 * 5, text: 'Team R-02 en route via Road R12.' },
    ],
    aiReasons: [
      'Immediate danger reported',
      'Medical emergency (injured person)',
      'Vulnerable person present (elderly)',
      'Multiple people affected (6)',
    ],
  },
  {
    id: 'E-101',
    disasterType: 'flood',
    description: 'Flood water rising near market. 8 people stranded on rooftop.',
    location: 'Zone B, Market Road',
    coords: { lat: 26.908, lng: 75.792 },
    peopleAffected: 8,
    injured: false,
    vulnerable: false,
    immediateDanger: true,
    priority: 'high',
    status: 'en_route',
    assignedTeam: 'Rescue Team R-03',
    assignedResource: 'Boat B-01',
    eta: 12,
    createdAt: Date.now() - 1000 * 60 * 14,
    updates: [
      { time: Date.now() - 1000 * 60 * 14, text: 'Emergency reported.' },
      { time: Date.now() - 1000 * 60 * 13, text: 'Triage: HIGH priority.' },
      { time: Date.now() - 1000 * 60 * 12, text: 'Boat B-01 assigned.' },
    ],
    aiReasons: [
      'Immediate danger (rising water)',
      'Multiple people affected (8)',
    ],
  },
  {
    id: 'E-103',
    disasterType: 'flood',
    description: 'Family of 15 trapped in two-storey house, water on ground floor.',
    location: 'Zone C, Flood Plain',
    coords: { lat: 26.92, lng: 75.775 },
    peopleAffected: 15,
    injured: false,
    vulnerable: true,
    immediateDanger: true,
    priority: 'high',
    status: 'reported',
    createdAt: Date.now() - 1000 * 60 * 3,
    updates: [
      { time: Date.now() - 1000 * 60 * 3, text: 'Emergency reported. Awaiting triage.' },
    ],
    aiReasons: [
      'Large number of people affected (15)',
      'Vulnerable members present',
      'Immediate danger reported',
    ],
  },
  {
    id: 'E-104',
    disasterType: 'flood',
    description: '3 people, one with chest pain, stranded near bridge.',
    location: 'Zone A, Old Bridge',
    coords: { lat: 26.917, lng: 75.785 },
    peopleAffected: 3,
    injured: true,
    vulnerable: false,
    immediateDanger: true,
    priority: 'critical',
    status: 'triaged',
    createdAt: Date.now() - 1000 * 60 * 2,
    updates: [
      { time: Date.now() - 1000 * 60 * 2, text: 'Emergency reported.' },
      { time: Date.now() - 1000 * 60 * 1, text: 'AI-assisted triage: CRITICAL (medical urgency).' },
    ],
    aiReasons: [
      'Medical urgency (chest pain)',
      'Immediate danger',
      'People affected (3)',
    ],
  },
];

export const initialResources: Resource[] = [
  {
    id: 'R-01',
    kind: 'rescue_vehicle',
    name: 'Rescue Vehicle R-01',
    status: 'assigned',
    location: 'Depot, Central',
    coords: { lat: 26.913, lng: 75.783 },
    distance: 2.1,
    eta: 6,
    capacity: 8,
    assignedTo: 'E-102',
  },
  {
    id: 'R-04',
    kind: 'rescue_vehicle',
    name: 'Rescue Vehicle R-04',
    status: 'available',
    location: 'North Station',
    coords: { lat: 26.922, lng: 75.78 },
    distance: 3.4,
    eta: 8,
    capacity: 10,
  },
  {
    id: 'R-03',
    kind: 'rescue_vehicle',
    name: 'Rescue Team R-03',
    status: 'assigned',
    location: 'Zone B',
    coords: { lat: 26.909, lng: 75.79 },
    assignedTo: 'E-101',
  },
  {
    id: 'B-01',
    kind: 'boat',
    name: 'Boat B-01',
    status: 'assigned',
    location: 'Flood Zone C',
    coords: { lat: 26.919, lng: 75.778 },
    capacity: 12,
    assignedTo: 'E-101',
  },
  {
    id: 'M-03',
    kind: 'medical_team',
    name: 'Medical Team M-03',
    status: 'assigned',
    location: 'Zone A',
    coords: { lat: 26.9145, lng: 75.782 },
    assignedTo: 'E-102',
  },
  {
    id: 'A-01',
    kind: 'ambulance',
    name: 'Ambulance A-01',
    status: 'available',
    location: 'Hospital H-01',
    coords: { lat: 26.91, lng: 75.77 },
    eta: 10,
  },
  {
    id: 'F-01',
    kind: 'food',
    name: 'Food Supplies F-01',
    status: 'low_stock',
    location: 'Relief Warehouse',
    coords: { lat: 26.906, lng: 75.772 },
  },
  {
    id: 'W-01',
    kind: 'water',
    name: 'Water W-01',
    status: 'available',
    location: 'Relief Warehouse',
    coords: { lat: 26.906, lng: 75.773 },
  },
  {
    id: 'MED-01',
    kind: 'medicines',
    name: 'Medicines MED-01',
    status: 'low_stock',
    location: 'Hospital H-01',
    coords: { lat: 26.91, lng: 75.771 },
  },
  {
    id: 'V-01',
    kind: 'volunteers',
    name: 'Volunteers V-01',
    status: 'available',
    location: 'Shelter A',
    coords: { lat: 26.905, lng: 75.785 },
    capacity: 20,
  },
];

export const initialRoads: Road[] = [
  {
    id: 'R12',
    name: 'Road R12',
    path: [
      { lat: 26.913, lng: 75.783 },
      { lat: 26.9145, lng: 75.7815 },
      { lat: 26.915, lng: 75.78 },
    ],
    blocked: false,
    conflict: false,
  },
  {
    id: 'R09',
    name: 'Road R09',
    path: [
      { lat: 26.913, lng: 75.783 },
      { lat: 26.918, lng: 75.784 },
      { lat: 26.922, lng: 75.78 },
    ],
    blocked: false,
  },
  {
    id: 'R05',
    name: 'Market Road R05',
    path: [
      { lat: 26.91, lng: 75.788 },
      { lat: 26.909, lng: 75.79 },
      { lat: 26.908, lng: 75.792 },
    ],
    blocked: false,
  },
];

export const initialShelters: Shelter[] = [
  {
    id: 'S-A',
    name: 'Shelter A — Community Hall',
    coords: { lat: 26.905, lng: 75.785 },
    occupancy: 80,
    capacity: 120,
    incoming: 12,
    food: 'ok',
    water: 'low',
    medicine: 'ok',
  },
  {
    id: 'S-B',
    name: 'Shelter B — School Building',
    coords: { lat: 26.9, lng: 75.795 },
    occupancy: 95,
    capacity: 100,
    incoming: 28,
    food: 'low',
    water: 'low',
    medicine: 'critical',
  },
  {
    id: 'S-C',
    name: 'Shelter C — Relief Camp',
    coords: { lat: 26.895, lng: 75.77 },
    occupancy: 40,
    capacity: 200,
    incoming: 0,
    food: 'ok',
    water: 'ok',
    medicine: 'ok',
  },
];

export const initialHospitals: Hospital[] = [
  {
    id: 'H-01',
    name: 'City Hospital H-01',
    coords: { lat: 26.91, lng: 75.77 },
    emergencyBeds: 12,
    emergencyBedsTotal: 20,
    icu: 6,
    icuTotal: 10,
    ventilators: 7,
    ventilatorsTotal: 10,
    isolationBeds: 4,
    isolationBedsTotal: 10,
    incoming: 17,
    status: 'operational',
    lastUpdated: Date.now() - 1000 * 60 * 8,
    edOpen: true,
    ambulanceReceiving: true,
    disasterCapacity: 'limited',
    ambulances: [
      { id: 'A01', status: 'available' },
      { id: 'A02', status: 'on_mission' },
      { id: 'A03', status: 'returning' },
    ],
    externalAmbulancesIncoming: 2,
    receivesTrauma: true,
    receivesMedical: true,
    receivesBurns: false,
    receivesPediatric: true,
    receivesCritical: true,
    doctors: 8,
    emergencySpecialists: 3,
    nurses: 21,
    bloodO: 'available',
    bloodA: 'available',
    bloodB: 'low',
    bloodAB: 'critical',
    oxygen: 'available',
    incomingCritical: 4,
    incomingSerious: 7,
    incomingModerate: 6,
    expectedNext30: 8,
    expectedNext2Hrs: 24,
    aiWarning: 'High patient inflow expected in the next 60 minutes.',
    aiWarningReasons: [
      'Flood zone expanding',
      '3 nearby emergencies active',
      'Ambulance requests increasing',
    ],
    accessibility: {
      mainEntrance: 'accessible',
      emergencyEntrance: 'accessible',
      notes: ['Road R17 blocked — use alternate route from south'],
    },
    tasks: [
      { id: 'T1', description: 'Prepare 5 ICU beds', priority: 'high', dueIn: 15, done: false },
      { id: 'T2', description: 'Confirm ambulance availability', priority: 'medium', dueIn: 30, done: false },
      { id: 'T3', description: 'Update medicine inventory', priority: 'low', dueIn: 60, done: false },
    ],
    resourceRequests: [
      { id: 'RR1', resource: 'Oxygen', quantity: 10, urgency: 'high', reason: 'Reserves depleting fast due to influx', status: 'pending', createdAt: Date.now() - 1000 * 60 * 10 },
      { id: 'RR2', resource: 'Ambulance', quantity: 2, urgency: 'medium', reason: 'Need additional transport for zone C', status: 'approved', createdAt: Date.now() - 1000 * 60 * 20 },
    ],
  },
  {
    id: 'H-02',
    name: 'Regional Hospital H-02',
    coords: { lat: 26.923, lng: 75.79 },
    emergencyBeds: 0,
    emergencyBedsTotal: 10,
    icu: 1,
    icuTotal: 4,
    ventilators: 2,
    ventilatorsTotal: 6,
    isolationBeds: 1,
    isolationBedsTotal: 5,
    incoming: 4,
    status: 'critical',
    lastUpdated: Date.now() - 1000 * 60 * 5,
    edOpen: true,
    ambulanceReceiving: false,
    disasterCapacity: 'critical',
    ambulances: [
      { id: 'A04', status: 'on_mission' },
      { id: 'A05', status: 'available' },
    ],
    externalAmbulancesIncoming: 0,
    receivesTrauma: true,
    receivesMedical: true,
    receivesBurns: true,
    receivesPediatric: false,
    receivesCritical: true,
    doctors: 4,
    emergencySpecialists: 1,
    nurses: 12,
    bloodO: 'low',
    bloodA: 'available',
    bloodB: 'available',
    bloodAB: 'available',
    oxygen: 'low',
    incomingCritical: 2,
    incomingSerious: 1,
    incomingModerate: 1,
    expectedNext30: 0,
    expectedNext2Hrs: 6,
    aiWarning: 'ER at full capacity — redirect new patients to H-01.',
    aiWarningReasons: ['Emergency beds at 0', 'ICU nearly full', 'Not receiving ambulances'],
    accessibility: {
      mainEntrance: 'accessible',
      emergencyEntrance: 'blocked',
      notes: ['Emergency entrance blocked by debris', 'Ambulances cannot reach from north entrance'],
    },
    tasks: [
      { id: 'T4', description: 'Clear emergency entrance debris', priority: 'critical', dueIn: 10, done: false },
      { id: 'T5', description: 'Arrange blood supply from H-01', priority: 'high', dueIn: 20, done: false },
    ],
    resourceRequests: [
      { id: 'RR3', resource: 'Blood (AB+)', quantity: 5, urgency: 'critical', reason: 'AB+ critically low, incoming trauma patient needs transfusion', status: 'pending', createdAt: Date.now() - 1000 * 60 * 5 },
    ],
  },
];

export const initialHazardZones: HazardZone[] = [
  {
    id: 'HZ-A',
    type: 'flood',
    label: 'Flood Zone A',
    center: { lat: 26.915, lng: 75.78 },
    radius: 600,
    expanding: false,
  },
  {
    id: 'HZ-C',
    type: 'flood',
    label: 'Flood Zone C',
    center: { lat: 26.92, lng: 75.775 },
    radius: 450,
    expanding: false,
  },
];

export const initialMissingPersons: MissingPerson[] = [
  {
    id: 'MP-104',
    name: 'Ramesh K.',
    age: 72,
    gender: 'male',
    lastLocation: 'Zone A, Riverside',
    description: 'Wearing white kurta, uses walking stick, grey hair.',
    contact: 'Family: 98xxxxxxxx',
    status: 'missing',
    reportedAt: Date.now() - 1000 * 60 * 30,
  },
  {
    id: 'MP-105',
    name: 'Anita S.',
    age: 34,
    gender: 'female',
    lastLocation: 'Zone B, Market',
    description: 'Red saree, carrying infant.',
    contact: 'Husband: 99xxxxxxxx',
    status: 'potential_match',
    reportedAt: Date.now() - 1000 * 60 * 20,
    possibleMatchAt: 'Shelter B',
    matchReasons: ['Approximate age', 'Reported location', 'Descriptive information'],
  },
];

export const initialFoundPersons: FoundPerson[] = [
  {
    id: 'FP-201',
    foundAt: 'Shelter B',
    description: 'Elderly male, white kurta, walking stick.',
    approxAge: 70,
    gender: 'male',
    registeredAt: Date.now() - 1000 * 60 * 15,
  },
];

export const initialMessages: Message[] = [
  {
    id: 'MSG-1',
    time: Date.now() - 1000 * 60 * 6,
    from: 'Authority',
    to: 'Rescue Team R-02',
    text: 'Proceed to Zone A, Riverside. 6 trapped, 1 injured, 1 vulnerable.',
    emergencyId: 'E-102',
  },
  {
    id: 'MSG-2',
    time: Date.now() - 1000 * 60 * 4,
    from: 'Hospital H-02',
    to: 'Medical Team M-03',
    text: 'Prepare for 1 critical incoming. ICU bed reserved.',
    emergencyId: 'E-102',
  },
];

export const initialNotifications: AppNotification[] = [
  {
    id: 'N-1',
    time: Date.now() - 1000 * 60 * 6,
    text: 'New critical SOS received — E-102, Zone A.',
    level: 'critical',
    roles: ['authority', 'rescue'],
    read: false,
  },
  {
    id: 'N-2',
    time: Date.now() - 1000 * 60 * 4,
    text: 'Your mission route changed. New ETA: 6 min.',
    level: 'high',
    roles: ['rescue'],
    read: false,
  },
  {
    id: 'N-3',
    time: Date.now() - 1000 * 60 * 3,
    text: '4 patients incoming to H-02. ETA 12 min.',
    level: 'high',
    roles: ['hospital'],
    read: false,
  },
  {
    id: 'N-4',
    time: Date.now() - 1000 * 60 * 2,
    text: '28 evacuees approaching Shelter B.',
    level: 'medium',
    roles: ['authority'],
    read: false,
  },
];
